{
 "title": "Home",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\")\n    |> map(fn: (r) => ({_value:r.name}))\n    |> unique()"
   },
   {
    "name": "site",
    "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"site\")\n    |> map(fn: (r) => ({_value:r.mirror}))\n    |> unique()"
   }
  ]
 },
 "panels": [
  {
   "title": "Site",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"site\")\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.mirror}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repo (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\" and r.mirror == \"${site}\" and r.name == \"${repo}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.mirror+\":\"+r.name}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo_lastupdate\" and r.mirror == \"${site}\" and r.name == \"${repo}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.mirror+\":\"+r.name+\" (lastupdate)\"}))"
    }
   ]
  },
  {
   "title": "${repo} (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\" and r.name == \"${repo}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.mirror}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${site} (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\" and r.mirror == \"${site}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.name}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${repo}",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\" and r.name == \"${repo}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.mirror}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${site}",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket : \"mirrorz\")\n    |> range(start: starttime, stop: stoptime)\n    |> filter(fn: (r) => r._measurement == \"repo\" and r.mirror == \"${site}\")\n    |> map(fn: (r) => ({_value:-r._value, _time:r._time, _field:r.name}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket:\"mirrorz\")\n        |> range(start: starttime, stop: stoptime)\n        |> filter(fn: (r) => r._measurement == \"repo\" and r._value != 0)\n        |> map(fn: (r) => ({_value:r._value,_time:r._time,_field:r.mirror+\" \"+r.name}))\n        |> tail(n:1)\n        |> group()\n        |> sort(columns: [\"_value\"], desc: true)\n        |> limit(n:32)\n        |> group(columns: [\"_field\"])\n        ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Earliest",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "starttime =  time(v: $__from * 1000000) //transform to ns. \nstoptime  = time(v: $__to * 1000000)\n\nfrom(bucket:\"mirrorz\")\n        |> range(start: starttime, stop: stoptime)\n        |> filter(fn: (r) => r._measurement == \"repo\" and r._value != 0)\n        |> map(fn: (r) => ({_value:r._value,_time:r._time,_field:r.mirror+\" \"+r.name}))\n        |> tail(n:1)\n        |> group()\n        |> sort(columns: [\"_value\"])\n        |> limit(n:32)\n        |> group(columns: [\"_field\"])\n        ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}